import { normalizeApiError, type RetryClassification } from "./errors";

interface ApiMeta {
  requestId: string;
  timestamp: string;
  correlationId?: string;
}

/**
 * Header a client may use to supply its own correlation identifier. Issue #1472:
 * this value is NEVER used as the canonical server request ID. It is accepted
 * only as an opaque correlation hint after validation.
 */
export const CLIENT_CORRELATION_HEADER = "x-request-id";

/**
 * Header the server echoes back with the (validated) client correlation ID, kept
 * separate from `x-request-id` so the two identifiers can never be confused.
 */
export const CORRELATION_ID_HEADER = "x-correlation-id";

/** Maximum accepted length of a client-supplied correlation ID. */
export const MAX_CORRELATION_ID_LENGTH = 128;

/**
 * Allowed characters for a client correlation ID: URL-safe token characters.
 * Excludes commas (so header-folded duplicates are rejected), whitespace, and
 * control characters that could enable log injection or header smuggling.
 */
const CORRELATION_ID_PATTERN = /^[A-Za-z0-9._~-]+$/;

interface RequestIdentity {
  /** Canonical, always server-generated request identifier. */
  requestId: string;
  /** Optional client-supplied correlation ID, present only when valid. */
  correlationId?: string;
}

/**
 * Validate an optional client-supplied correlation ID.
 *
 * Returns the value only when it is a non-empty, bounded, URL-safe token.
 * Missing, oversized, or malformed values (including header-folded duplicates,
 * which contain a comma) return `undefined` rather than throwing, so a bad
 * client header can never break request handling or displace the server ID.
 */
export function validateCorrelationId(raw: string | null | undefined): string | undefined {
  if (raw === null || raw === undefined) return undefined;
  const value = raw.trim();
  if (value.length === 0 || value.length > MAX_CORRELATION_ID_LENGTH) return undefined;
  if (!CORRELATION_ID_PATTERN.test(value)) return undefined;
  return value;
}

/**
 * Derive the request identity for a request. The request ID is always freshly
 * generated by the server; any incoming `x-request-id` is treated purely as a
 * candidate correlation ID and validated before use.
 */
function resolveRequestIdentity(request: Request): RequestIdentity {
  const correlationId = validateCorrelationId(request.headers.get(CLIENT_CORRELATION_HEADER));
  return {
    requestId: crypto.randomUUID(),
    ...(correlationId === undefined ? {} : { correlationId }),
  };
}

interface SuccessEnvelope<T> {
  data: T;
  meta: ApiMeta;
}

interface ErrorEnvelope {
  error: {
    code: string;
    details?: unknown;
    message: string;
    retryable: boolean;
    retryClassification: RetryClassification;
    retryAfter?: number;
  };
  meta: ApiMeta;
}

export const CACHE_POLICIES = {
  NO_STORE: "no-store",
  PUBLIC_5_MINUTES: "public, max-age=300",
  PUBLIC_IMMUTABLE: "public, max-age=31536000, immutable",
  PUBLIC_REVALIDATE: "public, max-age=0, must-revalidate",
} as const;

export const JSON_SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
} as const;

type CachePolicy = keyof typeof CACHE_POLICIES;

interface ResponseOptions {
  cachePolicy?: CachePolicy;
  headers?: HeadersInit;
  status?: number;
}

function getRequestId(request: Request) {
  return resolveRequestIdentity(request).requestId;
}

function responseHeaders(
  requestId: string,
  headers?: HeadersInit,
  cachePolicy: CachePolicy = "NO_STORE",
  correlationId?: string,
) {
  const result = new Headers(headers);
  const cacheControl = CACHE_POLICIES[cachePolicy];
  const suppliedCacheControl = result.get("cache-control");

  if (suppliedCacheControl !== null && suppliedCacheControl !== cacheControl) {
    throw new TypeError(
      "Cache-Control must be configured with a named cache policy; conflicting directives are not allowed",
    );
  }

  result.set("cache-control", cacheControl);
  result.set("content-type", "application/json; charset=utf-8");
  result.set("x-request-id", requestId);
  if (correlationId !== undefined) {
    result.set(CORRELATION_ID_HEADER, correlationId);
  }
  for (const [name, value] of Object.entries(JSON_SECURITY_HEADERS)) {
    result.set(name, value);
  }
  return result;
}

function meta(requestId: string, correlationId?: string): ApiMeta {
  return {
    requestId,
    timestamp: new Date().toISOString(),
    ...(correlationId === undefined ? {} : { correlationId }),
  };
}

function enforceJsonSecurityHeaders(response: Response) {
  const contentType = response.headers.get("content-type")?.toLowerCase();
  if (!contentType?.includes("application/json")) {
    return response;
  }

  const securedResponse = new Response(response.body, response);
  for (const [name, value] of Object.entries(JSON_SECURITY_HEADERS)) {
    securedResponse.headers.set(name, value);
  }
  return securedResponse;
}

export function apiSuccess<T>(request: Request, data: T, options: ResponseOptions = {}) {
  const { requestId, correlationId } = resolveRequestIdentity(request);
  const body: SuccessEnvelope<T> = { data, meta: meta(requestId, correlationId) };

  return new Response(JSON.stringify(body), {
    status: options.status ?? 200,
    headers: responseHeaders(requestId, options.headers, options.cachePolicy, correlationId),
  });
}

export function jsonResponse(
  requestOrRequestId: Request | string,
  body: unknown,
  options: ResponseOptions = {},
) {
  const requestId =
    typeof requestOrRequestId === "string" ? requestOrRequestId : getRequestId(requestOrRequestId);

  return new Response(JSON.stringify(body), {
    status: options.status ?? 200,
    headers: responseHeaders(requestId, options.headers, options.cachePolicy),
  });
}

export function apiFailure(request: Request, caught: unknown) {
  const { requestId, correlationId } = resolveRequestIdentity(request);
  const error = normalizeApiError(caught);
  const body: ErrorEnvelope = {
    error: {
      code: error.code,
      message: error.message,
      retryable: error.retryable,
      retryClassification: error.retryClassification,
      ...(error.retryAfterSeconds === undefined ? {} : { retryAfter: error.retryAfterSeconds }),
      ...(error.details === undefined ? {} : { details: error.details }),
    },
    meta: meta(requestId, correlationId),
  };

  const headers = responseHeaders(requestId, undefined, undefined, correlationId);
  if (error.retryAfterSeconds !== undefined) {
    headers.set("retry-after", String(error.retryAfterSeconds));
  }

  return new Response(JSON.stringify(body), {
    status: error.status,
    headers,
  });
}

export async function handleApiRequest(
  request: Request,
  handler: () => Response | Promise<Response>,
) {
  try {
    return enforceJsonSecurityHeaders(await handler());
  } catch (error) {
    return apiFailure(request, error);
  }
}

export type { ApiMeta, CachePolicy, ErrorEnvelope, ResponseOptions, SuccessEnvelope };
export type { RequestIdentity };
